/**
 * Componente Curricular: Módulo Integrado de Programação
 * Autor: Daniel Fernandes Campos e Esdras Evangelista de sena santos
 * Data: 20/09/2019
 *
 * Declaro que este código foi elaborado pela dupla de forma individual e
 * não contém nenhum trecho de código de outro colega ou de outro autor,
 * tais como provindos de livros e apostilas, e páginas ou documentos
 * eletrônicos da Internet. Qualquer trecho de código de outra autoria que
 * uma citação para o  não a minha está destacado com  autor e a fonte do
 * código, e estou ciente que estes trechos não serão considerados para fins
 * de avaliação. Alguns trechos do código podem coincidir com de outros
 * colegas pois estes foram discutidos em sessões tutorias.
 */
package View;


import Controler.MainCotroler;
import Util.EstruturaDeDados.Iterator;


public class Tela extends javax.swing.JFrame {
    public static MainCotroler controler;// nota foi criado como statico pois 
    //so existe 1 controler no sistema que é esse aqui e sera acessado por outras classes
    
    /**
     * Creates new form TelalInicial
     */
    public Tela() {
        initComponents();
    }
    /**
     * Função que editaos labels contendo os index dos elementos sempre que uma
     * ação é feita
     */
    private void atuaizar_labels_index_info(){
        this.label_index_extacionamento.setText("Estacionamento: "+Tela.controler.getEstacionamento_index());
        String bancos_String = "";
        Iterator it = Tela.controler.getBancos().iterator();
        while(it.hasNext()){
            bancos_String+= it.next() ;
            bancos_String+=" ";
        }
        System.out.println("Bancos:" + bancos_String );
        this.label_lista_index_bancos.setText("Bancos:" + bancos_String );
        String coletas_String = "";
        it = Tela.controler.getColetas().iterator();
        while(it.hasNext()){
            coletas_String+=it.next();
            coletas_String+=" ";
        }
        System.out.println("Coleta: "+ coletas_String);
        this.label_lista_index_coletas.setText("Coleta: "+ coletas_String);
        this.label_num_vertices.setText("Numero de vertices no grafo: "+ Tela.controler.getGrafo().getNumVertices() );
        // Essa parte do codigo atualiza os labels de informaçao da tela do dijkstra
        this.label_index_extacionamento_dijskstra.setText("Estacionamento: "+Tela.controler.getEstacionamento_index());
        this.label_lista_index_bancos_dijskstra.setText("Bancos:" + bancos_String );
        this.label_lista_index_coletas_dijskstra.setText("Coleta: "+ coletas_String);
        this.label_num_vertices_dijskstra.setText("Numero de vertices no grafo: "+ Tela.controler.getGrafo().getNumVertices() );
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frame_Geral = new javax.swing.JInternalFrame();
        Panel_Geral = new javax.swing.JTabbedPane();
        Panel_Vertice = new javax.swing.JPanel();
        text_adiciona_vertice_index = new javax.swing.JTextField();
        buton_adicionar_vertice = new javax.swing.JButton();
        text_swap_vertice_index2 = new javax.swing.JTextField();
        buton_swap_vertice = new javax.swing.JButton();
        text_path_file = new javax.swing.JTextField();
        buton_importar = new javax.swing.JButton();
        label_index_extacionamento = new javax.swing.JLabel();
        label_lista_index_coletas = new javax.swing.JLabel();
        label_lista_index_bancos = new javax.swing.JLabel();
        label_info_swap_vertice = new javax.swing.JLabel();
        text_remover_vertice = new javax.swing.JTextField();
        text_swap_vertice_index1 = new javax.swing.JTextField();
        buton_remover_vertice = new javax.swing.JButton();
        comboBox_tipo_vertice_adicionado = new javax.swing.JComboBox<>();
        label_info_tipo_vertice_adicionado = new javax.swing.JLabel();
        label_num_vertices = new javax.swing.JLabel();
        Panel_Aresta = new javax.swing.JPanel();
        text_aresta_index1 = new javax.swing.JTextField();
        label_info_ligaçoes = new javax.swing.JLabel();
        text_aresta_valor = new javax.swing.JTextField();
        text_aresta_index2 = new javax.swing.JTextField();
        Label_Remover_Aresta_info = new javax.swing.JLabel();
        buton_atualizar_aresta = new javax.swing.JButton();
        Panel_Dijkstra = new javax.swing.JPanel();
        Frame_dijkstra_interaçao = new javax.swing.JLayeredPane();
        text_start_index = new javax.swing.JTextField();
        label_infostart_index = new javax.swing.JLabel();
        text_coleta_index = new javax.swing.JTextField();
        text_banco_index = new javax.swing.JTextField();
        buton_pathfinder = new javax.swing.JButton();
        label_path_Start_Coleta = new javax.swing.JLabel();
        label_path_Coleta_Banco = new javax.swing.JLabel();
        label_path_Start_Banco = new javax.swing.JLabel();
        label_num_vertices_dijskstra = new javax.swing.JLabel();
        label_index_extacionamento_dijskstra = new javax.swing.JLabel();
        label_lista_index_coletas_dijskstra = new javax.swing.JLabel();
        label_lista_index_bancos_dijskstra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Frame_Geral.setTitle("Forte Seguro");
        Frame_Geral.setToolTipText("");
        Frame_Geral.setVisible(true);

        Panel_Vertice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        text_adiciona_vertice_index.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_adiciona_vertice_index.setText("Para adiciona pontos digite o numero de pontos que deja adicionar aqui.");
        text_adiciona_vertice_index.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_adiciona_vertice_indexFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_adiciona_vertice_indexFocusLost(evt);
            }
        });

        buton_adicionar_vertice.setText("Adicionar");
        buton_adicionar_vertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_adicionar_verticeActionPerformed(evt);
            }
        });

        text_swap_vertice_index2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_swap_vertice_index2.setText("Index 2");
        text_swap_vertice_index2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text_swap_vertice_index2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_swap_vertice_index2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_swap_vertice_index2FocusLost(evt);
            }
        });

        buton_swap_vertice.setText("Troca");
        buton_swap_vertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_swap_verticeActionPerformed(evt);
            }
        });

        text_path_file.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_path_file.setText("Para importa o arquivo digite aqui o caminho do arquivo.( Exemplo: Files\\\\Pontos.txt )");
        text_path_file.setToolTipText("");
        text_path_file.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text_path_file.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_path_fileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_path_fileFocusLost(evt);
            }
        });

        buton_importar.setText("Importar");
        buton_importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_importarActionPerformed(evt);
            }
        });

        label_index_extacionamento.setText("Estacionamento: 0");

        label_lista_index_coletas.setText("Coletas: ");

        label_lista_index_bancos.setText("Bancos: ");

        label_info_swap_vertice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_info_swap_vertice.setText("Para troca 2 pontos de posiçao digite abaixo:");

        text_remover_vertice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_remover_vertice.setText("Para remover digite o index do pontos aqui.");
        text_remover_vertice.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text_remover_vertice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_remover_verticeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_remover_verticeFocusLost(evt);
            }
        });

        text_swap_vertice_index1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_swap_vertice_index1.setText("Index 1");
        text_swap_vertice_index1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        text_swap_vertice_index1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_swap_vertice_index1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_swap_vertice_index1FocusLost(evt);
            }
        });

        buton_remover_vertice.setText("Remover");
        buton_remover_vertice.setToolTipText("");
        buton_remover_vertice.setActionCommand("Remover_vertice");
        buton_remover_vertice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buton_remover_vertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_remover_verticeActionPerformed(evt);
            }
        });

        comboBox_tipo_vertice_adicionado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cruzamento", "Coleta", "Banco" }));

        label_info_tipo_vertice_adicionado.setText("Escolha o tipo do vertice adicionado, abaixo");

        label_num_vertices.setText("Numero de vertices no grafo: 1");

        javax.swing.GroupLayout Panel_VerticeLayout = new javax.swing.GroupLayout(Panel_Vertice);
        Panel_Vertice.setLayout(Panel_VerticeLayout);
        Panel_VerticeLayout.setHorizontalGroup(
            Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_path_file)
            .addComponent(buton_importar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_VerticeLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_VerticeLayout.createSequentialGroup()
                        .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_info_swap_vertice, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_remover_vertice, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_VerticeLayout.createSequentialGroup()
                                .addComponent(text_swap_vertice_index1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(text_swap_vertice_index2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_VerticeLayout.createSequentialGroup()
                        .addComponent(text_adiciona_vertice_index, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_VerticeLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(comboBox_tipo_vertice_adicionado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label_info_tipo_vertice_adicionado))
                        .addGap(18, 18, 18)))
                .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buton_adicionar_vertice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buton_remover_vertice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buton_swap_vertice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
            .addGroup(Panel_VerticeLayout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_num_vertices)
                    .addComponent(label_index_extacionamento)
                    .addComponent(label_lista_index_coletas)
                    .addComponent(label_lista_index_bancos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_VerticeLayout.setVerticalGroup(
            Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_VerticeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_adicionar_vertice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_adiciona_vertice_index, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_VerticeLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(label_info_tipo_vertice_adicionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBox_tipo_vertice_adicionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buton_remover_vertice, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_remover_vertice, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(label_info_swap_vertice)
                .addGap(18, 18, 18)
                .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_VerticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_swap_vertice_index2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(text_swap_vertice_index1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buton_swap_vertice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(label_num_vertices, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_index_extacionamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_lista_index_coletas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_lista_index_bancos)
                .addGap(18, 18, 18)
                .addComponent(text_path_file, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buton_importar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        text_adiciona_vertice_index.getAccessibleContext().setAccessibleName("text_index_adiciona_vertice");
        buton_adicionar_vertice.getAccessibleContext().setAccessibleName("buton_adicionar");
        text_swap_vertice_index2.getAccessibleContext().setAccessibleName("text_swap_index2");
        text_swap_vertice_index2.getAccessibleContext().setAccessibleDescription("");
        buton_swap_vertice.getAccessibleContext().setAccessibleName("buton_swap");
        text_path_file.getAccessibleContext().setAccessibleName("text_path_file");
        buton_importar.getAccessibleContext().setAccessibleName("buton_Importar");
        label_index_extacionamento.getAccessibleContext().setAccessibleName("label_estacionamento");
        label_info_swap_vertice.getAccessibleContext().setAccessibleName("text_info_swap");
        text_remover_vertice.getAccessibleContext().setAccessibleName("text_index_remover_vertice");
        text_swap_vertice_index1.getAccessibleContext().setAccessibleName("text_swap_index1");
        buton_remover_vertice.getAccessibleContext().setAccessibleName("buton_remover");

        Panel_Geral.addTab("Adicionar / Remover Vertice", Panel_Vertice);
        Panel_Vertice.getAccessibleContext().setAccessibleName("frame_vertice");
        Panel_Vertice.getAccessibleContext().setAccessibleDescription("");

        Panel_Aresta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        text_aresta_index1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_aresta_index1.setText("Index do primeiro ponto");
        text_aresta_index1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_aresta_index1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_aresta_index1FocusLost(evt);
            }
        });

        label_info_ligaçoes.setText("Para remover ou adicionar  Ligaçao digite a baixo o index dos 2 pontos  e novo valor da ligação deles");

        text_aresta_valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_aresta_valor.setText("Valor da nova coneção");
        text_aresta_valor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_aresta_valorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_aresta_valorFocusLost(evt);
            }
        });

        text_aresta_index2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_aresta_index2.setText("Index do segundo ponto");
        text_aresta_index2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_aresta_index2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_aresta_index2FocusLost(evt);
            }
        });

        Label_Remover_Aresta_info.setText("Para remover ligação coleque '0'");

        buton_atualizar_aresta.setText("Atualizar");
        buton_atualizar_aresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_atualizar_arestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ArestaLayout = new javax.swing.GroupLayout(Panel_Aresta);
        Panel_Aresta.setLayout(Panel_ArestaLayout);
        Panel_ArestaLayout.setHorizontalGroup(
            Panel_ArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ArestaLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(Panel_ArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_info_ligaçoes, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_ArestaLayout.createSequentialGroup()
                        .addComponent(text_aresta_index1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(text_aresta_index2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Panel_ArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Remover_Aresta_info)
                            .addComponent(text_aresta_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_ArestaLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(buton_atualizar_aresta, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        Panel_ArestaLayout.setVerticalGroup(
            Panel_ArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ArestaLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(label_info_ligaçoes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(Panel_ArestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_aresta_index2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_aresta_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_aresta_index1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Remover_Aresta_info, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(buton_atualizar_aresta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );

        text_aresta_index1.getAccessibleContext().setAccessibleName("text_index_ponto1");
        label_info_ligaçoes.getAccessibleContext().setAccessibleName("text_info_ligaçoes");
        text_aresta_valor.getAccessibleContext().setAccessibleName("text_valor_coneçao");
        text_aresta_index2.getAccessibleContext().setAccessibleName("text_index_ponto2");
        Label_Remover_Aresta_info.getAccessibleContext().setAccessibleName("label_info_remover_ligaçao");
        buton_atualizar_aresta.getAccessibleContext().setAccessibleName("buton_atualizar_ligaçao");

        Panel_Geral.addTab("Adicionar / Remover Ligaçao", Panel_Aresta);
        Panel_Aresta.getAccessibleContext().setAccessibleName("frame_aresta");

        Panel_Dijkstra.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Frame_dijkstra_interaçao.setBackground(new java.awt.Color(0, 0, 0));
        Frame_dijkstra_interaçao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Frame_dijkstra_interaçao.setToolTipText("");

        text_start_index.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_start_index.setText("Index Start");
        text_start_index.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_start_indexFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_start_indexFocusLost(evt);
            }
        });

        label_infostart_index.setText("Para estacionaento digite apenas um expaço (' ')");

        text_coleta_index.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_coleta_index.setText("Index do ponto de colta");
        text_coleta_index.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_coleta_indexFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_coleta_indexFocusLost(evt);
            }
        });

        text_banco_index.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_banco_index.setText("Index do Banco");
        text_banco_index.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text_banco_indexFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                text_banco_indexFocusLost(evt);
            }
        });

        buton_pathfinder.setText("Calcular o MENOR caminho entre A e B");
        buton_pathfinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_pathfinderActionPerformed(evt);
            }
        });

        Frame_dijkstra_interaçao.setLayer(text_start_index, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Frame_dijkstra_interaçao.setLayer(label_infostart_index, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Frame_dijkstra_interaçao.setLayer(text_coleta_index, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Frame_dijkstra_interaçao.setLayer(text_banco_index, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Frame_dijkstra_interaçao.setLayer(buton_pathfinder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Frame_dijkstra_interaçaoLayout = new javax.swing.GroupLayout(Frame_dijkstra_interaçao);
        Frame_dijkstra_interaçao.setLayout(Frame_dijkstra_interaçaoLayout);
        Frame_dijkstra_interaçaoLayout.setHorizontalGroup(
            Frame_dijkstra_interaçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_dijkstra_interaçaoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(Frame_dijkstra_interaçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_dijkstra_interaçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Frame_dijkstra_interaçaoLayout.createSequentialGroup()
                            .addComponent(text_start_index)
                            .addGap(158, 158, 158)
                            .addComponent(text_coleta_index, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(335, 335, 335))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Frame_dijkstra_interaçaoLayout.createSequentialGroup()
                            .addComponent(label_infostart_index)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 684, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_dijkstra_interaçaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Frame_dijkstra_interaçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Frame_dijkstra_interaçaoLayout.createSequentialGroup()
                                .addComponent(buton_pathfinder, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269))
                            .addComponent(text_banco_index, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(104, 104, 104))
        );
        Frame_dijkstra_interaçaoLayout.setVerticalGroup(
            Frame_dijkstra_interaçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Frame_dijkstra_interaçaoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Frame_dijkstra_interaçaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_coleta_index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_start_index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_banco_index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_infostart_index)
                .addGap(53, 53, 53)
                .addComponent(buton_pathfinder)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        text_start_index.getAccessibleContext().setAccessibleName("text_index_start");
        text_start_index.getAccessibleContext().setAccessibleDescription("");
        label_infostart_index.getAccessibleContext().setAccessibleName("label_info_start_vertice");
        text_coleta_index.getAccessibleContext().setAccessibleName("text_index_coleta");
        text_banco_index.getAccessibleContext().setAccessibleName("text_index_banco");
        buton_pathfinder.getAccessibleContext().setAccessibleName("buton_calcular_caminho");

        label_path_Start_Coleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_path_Start_Coleta.setText("Path do Inicio para Coleta: ");

        label_path_Coleta_Banco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_path_Coleta_Banco.setText("Path de Coleta para Banco: ");

        label_path_Start_Banco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_path_Start_Banco.setText("Path do inicioi para Banco: ");

        label_num_vertices_dijskstra.setText("Numero de vertices no grafo: 1");

        label_index_extacionamento_dijskstra.setText("Estacionamento: 0");

        label_lista_index_coletas_dijskstra.setText("Coletas: ");

        label_lista_index_bancos_dijskstra.setText("Bancos: ");

        javax.swing.GroupLayout Panel_DijkstraLayout = new javax.swing.GroupLayout(Panel_Dijkstra);
        Panel_Dijkstra.setLayout(Panel_DijkstraLayout);
        Panel_DijkstraLayout.setHorizontalGroup(
            Panel_DijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Frame_dijkstra_interaçao)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DijkstraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_DijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_path_Start_Coleta, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_path_Start_Banco, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_path_Coleta_Banco, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(Panel_DijkstraLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addGroup(Panel_DijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_num_vertices_dijskstra)
                    .addComponent(label_index_extacionamento_dijskstra)
                    .addComponent(label_lista_index_coletas_dijskstra)
                    .addComponent(label_lista_index_bancos_dijskstra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_DijkstraLayout.setVerticalGroup(
            Panel_DijkstraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DijkstraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Frame_dijkstra_interaçao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_num_vertices_dijskstra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_index_extacionamento_dijskstra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_lista_index_coletas_dijskstra, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_lista_index_bancos_dijskstra)
                .addGap(25, 25, 25)
                .addComponent(label_path_Start_Coleta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_path_Coleta_Banco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(label_path_Start_Banco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Frame_dijkstra_interaçao.getAccessibleContext().setAccessibleName("frame_grafo");
        label_path_Start_Coleta.getAccessibleContext().setAccessibleName("label_mostra_caminho");

        Panel_Geral.addTab("Dijkstra", null, Panel_Dijkstra, "");
        Panel_Dijkstra.getAccessibleContext().setAccessibleName("frame_grafo");

        javax.swing.GroupLayout Frame_GeralLayout = new javax.swing.GroupLayout(Frame_Geral.getContentPane());
        Frame_Geral.getContentPane().setLayout(Frame_GeralLayout);
        Frame_GeralLayout.setHorizontalGroup(
            Frame_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Geral)
        );
        Frame_GeralLayout.setVerticalGroup(
            Frame_GeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Geral)
        );

        Panel_Geral.getAccessibleContext().setAccessibleName("multFrame");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Frame_Geral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Frame_Geral)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_aresta_index1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_aresta_index1FocusGained
        // TODO add your handling code here:
        text_aresta_index1.setText("");
    }//GEN-LAST:event_text_aresta_index1FocusGained

    private void text_aresta_index2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_aresta_index2FocusGained
        // TODO add your handling code here:
        text_aresta_index2.setText("");
    }//GEN-LAST:event_text_aresta_index2FocusGained

    private void text_aresta_valorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_aresta_valorFocusGained
        // TODO add your handling code here:
        text_aresta_valor.setText("");
    }//GEN-LAST:event_text_aresta_valorFocusGained

    private void text_start_indexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_start_indexFocusGained
        // TODO add your handling code here:
        text_start_index.setText("");
    }//GEN-LAST:event_text_start_indexFocusGained

    private void text_coleta_indexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_coleta_indexFocusGained
        // TODO add your handling code here:
        text_coleta_index.setText("");
    }//GEN-LAST:event_text_coleta_indexFocusGained

    private void text_banco_indexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_banco_indexFocusGained
        // TODO add your handling code here:
        text_banco_index.setText("");
    }//GEN-LAST:event_text_banco_indexFocusGained

    private void buton_atualizar_arestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_atualizar_arestaActionPerformed
        // TODO add your handling code here:
        int index1 = 0;
        int index2 = 0;
        int valor = 0;
        try{
            index1 = Integer.parseUnsignedInt( this.text_aresta_index1.getText() );
            index2 = Integer.parseUnsignedInt( this.text_aresta_index2.getText() );
            if( !(this.text_aresta_valor.getText() == "") )
            valor = Integer.parseUnsignedInt( this.text_aresta_valor.getText() );
        }catch(NumberFormatException e){
            ERRO.dialogErro("Erro Numero nao digitado", "Porfavor coloque numeros nao negativos nos campos");
            return;
        }
        if( index1 == index2 ){
            ERRO.dialogErro("Erro no swap", "Dgite numeros nao iguais por favor");
        }else if( index1 < 0 || index1 > Tela.controler.getGrafo().getNumVertices()  ){
            ERRO.dialogErro("Erro no swap index 1", "O numero no index 1 é menor que zero ou maior que o numero de vertices do grafo");
        }else{
            Tela.controler.editarAresta(index1, index2, valor);
            ERRO.dialogErro("SUCESSO", "A ligação de "+ index1+" e "+index2 + " foi adicionada com sucesso");
        }
    }//GEN-LAST:event_buton_atualizar_arestaActionPerformed

    private void buton_remover_verticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_remover_verticeActionPerformed
        // TODO add your handling code here:
        int index1 = 0;
        try{
            index1 = Integer.parseUnsignedInt( this.text_remover_vertice.getText() );
        }catch(NumberFormatException e){
            ERRO.dialogErro("Erro Numero nao digitado", "Porfavor coloque um numero valido no campo de remover vertice");
            //    System.out.println("rola nao");
            return;
        }
        if( index1 < 0 || index1 > Tela.controler.getGrafo().getNumVertices()-1  ){
            ERRO.dialogErro("Erro no remover vertice", "Coloque um numero de index de vertices do grafo");
        }else if( Tela.controler.getEstacionamento_index() == index1 ){
            ERRO.dialogErro("AI NÃO", "NÃO é possivel REMOVER o ESTACIONAMENTO");
        }else{
            if( Tela.controler.remover_vertice(index1)){
                atuaizar_labels_index_info();
                ERRO.dialogErro("SUCESSO", "O vertice de index "+ index1 +" foi removido do grafo e tadas as suas ligações");
            }else
                ERRO.dialogErro("Erro ao remover", "Por algum motivo não foi poscivel remover o vertice "+index1);
        }
    }//GEN-LAST:event_buton_remover_verticeActionPerformed

    private void text_swap_vertice_index1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_swap_vertice_index1FocusGained
        // TODO add your handling code here:
        text_swap_vertice_index1.setText("");
    }//GEN-LAST:event_text_swap_vertice_index1FocusGained

    private void text_remover_verticeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_remover_verticeFocusGained
        // TODO add your handling code here:
        text_remover_vertice.setText("");
    }//GEN-LAST:event_text_remover_verticeFocusGained

    private void buton_importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_importarActionPerformed
        // TODO add your handling code here:
        try {
            controler.loadMatrizFromFile(this.text_path_file.getText());
        } catch (Exception ex) {
            ERRO.dialogErro("Erro na leitura do Arquivo", "Ocorreu um erro na leitura do arquivo, verifique se o caminho informado esta certo ou se o arquivo existe");
           // Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
           return;
        }
        atuaizar_labels_index_info();
        ERRO.dialogErro("Arquivo aberto com sucesso", "O arquivo foi aberto com sucesso");
        //System.out.println(controler.getGrafo().getNumVertices());
    }//GEN-LAST:event_buton_importarActionPerformed

    private void text_path_fileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_path_fileFocusGained
        // TODO add your handling code here:
        if("Para importa o arquivo digite aqui o caminho do arquivo.( Exemplo: Files\\\\Pontos.txt )".equals(this.text_path_file.getText()))
            text_path_file.setText("");
    }//GEN-LAST:event_text_path_fileFocusGained

    private void buton_swap_verticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_swap_verticeActionPerformed
        // TODO add your handling code here:
        int index1 = 0;
        int index2 = 0;
        try{
            index1 = Integer.parseUnsignedInt( this.text_swap_vertice_index1.getText() );
            index2 = Integer.parseUnsignedInt( this.text_swap_vertice_index2.getText() );
        }catch(NumberFormatException e){
            ERRO.dialogErro("Erro Numero nao digitado", "Porfavor coloque numeros validos no campo de troca de vertice");
            //    System.out.println("rola nao");
            return;
        }
        if( index1 == index2 ){
            ERRO.dialogErro("Erro no swap", "Dgite numeros nao iguais por favor");
        }else if( index1 < 0 || index1 > Tela.controler.getGrafo().getNumVertices()-1  ){
            ERRO.dialogErro("Erro no swap index 1", "O numero no index 1 é menor que zero ou maior que o numero de vertices do grafo, porfavor coloque um numero valido");
        }else if( index2 < 0 || index2 > Tela.controler.getGrafo().getNumVertices()-1  ){
            ERRO.dialogErro("Erro no swap index 2", "O numero no index 2 é menor que zero ou maior que o numero de vertices do grafo, porfavor coloque um numero valido");
        }else{
            if( Tela.controler.swapVertices(index1, index2) ){
                atuaizar_labels_index_info();
                ERRO.dialogErro("SUCESSO", "Os vertices "+index1+" e "+index2+" foram trocados com sucesso");
            }else{
                ERRO.dialogErro("FALHA", "A troca dos vertices "+index1+" e "+index2+" não foi efetuada");
            }
        }
    }//GEN-LAST:event_buton_swap_verticeActionPerformed

    private void text_swap_vertice_index2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_swap_vertice_index2FocusGained
        // TODO add your handling code here:
        text_swap_vertice_index2.setText("");
    }//GEN-LAST:event_text_swap_vertice_index2FocusGained

//FUNCIONANDO
    private void buton_adicionar_verticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_adicionar_verticeActionPerformed
        // TODO add your handling code here:
        //System.out.println(controler.getGrafo().getNumVertices());
        int c = 0;
        try{
            c = Integer.parseUnsignedInt( this.text_adiciona_vertice_index.getText() );
        }catch(NumberFormatException e){
            ERRO.dialogErro("Erro Numero nao digitado", "Porfavor coloque um numero inteiro positivo no Primeiro campo de texto");
            //    System.out.println("rola nao");
            return;
        }
        if(c <= 0){
            ERRO.dialogErro("Numero digitado invalido", "O numero digitado no Primeiro campo é igual ou menor que zero.\n"
                + " Porfavor entre um numero inteiro maior que zero");
            //    System.out.println("DIGITA CERTO AE");
        }else{
            int tipo =0, selecionado = comboBox_tipo_vertice_adicionado.getSelectedIndex();
            String tipo_String = "";
            if(selecionado == 0){
                tipo=0;
                tipo_String = "Cruzamento";
            }else if(selecionado == 1){
                tipo = -3;
                tipo_String = "Coleta";
            }else if(selecionado == 2){
                tipo = -2;
                tipo_String = "Banco";
            }
            controler.add_vertice(c, tipo );
            atuaizar_labels_index_info();
            ERRO.dialogErro("SUCESSO", "Foi adicionado "+ c +" vertices do tipo "+tipo_String);
        }
        //System.out.println(controler.getGrafo().getNumVertices());
    }//GEN-LAST:event_buton_adicionar_verticeActionPerformed

    private void text_adiciona_vertice_indexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_adiciona_vertice_indexFocusGained
        // TODO add your handling code here:
        text_adiciona_vertice_index.setText("");
    }//GEN-LAST:event_text_adiciona_vertice_indexFocusGained

    private void buton_pathfinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_pathfinderActionPerformed
        // TODO add your handling code here:
        int indexStart;
        int indexColeta;
        int indexBanco;
        try{
            if(" ".equals(this.text_start_index.getText()))
                indexStart = Tela.controler.getEstacionamento_index();
            else
                indexStart = Integer.parseUnsignedInt( this.text_start_index.getText() );
            indexColeta = Integer.parseUnsignedInt( this.text_coleta_index.getText() );
            indexBanco = Integer.parseUnsignedInt( this.text_banco_index.getText() );
        }catch(NumberFormatException e){
            ERRO.dialogErro("Erro Numero nao digitado", "Porfavor coloque numeros validos nos campos de texto");
            //    System.out.println("rola nao");
            return;
        }
        if( indexStart>Tela.controler.getGrafo().getNumVertices() || indexStart<0 ){
            ERRO.dialogErro("Erro Campo 1", "O index de Start não esta na matriz");
            return;
        }
        if( indexColeta>Tela.controler.getGrafo().getNumVertices() || indexColeta<0 ){
            ERRO.dialogErro("Erro Campo 2", "O index de Coleta não esta na matriz");
            return;
        }
        if( indexBanco>Tela.controler.getGrafo().getNumVertices() || indexBanco<0 ){
            ERRO.dialogErro("Erro Campo 3", "O index de Banco não esta na matriz");
            return;
        }
        String text_dijkstra = Tela.controler.dijkstraDuplo(indexStart, indexColeta, indexBanco);
        if("CAMINHO IMPOCIVEL" == text_dijkstra){
            ERRO.dialogErro("ERRO", "Caminho inalcançavel.");
            return;
        }
        char[] dijkstra_char = new char[text_dijkstra.length()];
        text_dijkstra.getChars(0, text_dijkstra.length(), dijkstra_char, 0);
        String label_1 = "";
        String label_2 = "";
        String label_3 = "";
        int i = 0;
        for(  ; dijkstra_char[i] != '\n'; i++ )
            label_1+=text_dijkstra.charAt(i);
        i++;
        for(  ; dijkstra_char[i] != '\n'; i++ )
            label_2+=text_dijkstra.charAt(i);
        while( i<dijkstra_char.length ){
            label_3+=text_dijkstra.charAt(i);
            i++;
        }
        this.label_path_Start_Coleta.setText(label_1);
        this.label_path_Coleta_Banco.setText(label_2);
        this.label_path_Start_Banco.setText(label_3);
    }//GEN-LAST:event_buton_pathfinderActionPerformed

    private void text_aresta_index1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_aresta_index1FocusLost
        // TODO add your handling code here:
        if(this.text_aresta_index1.getText().length() == 0)
            this.text_aresta_index1.setText("Index do primeiro ponto");
    }//GEN-LAST:event_text_aresta_index1FocusLost

    private void text_aresta_index2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_aresta_index2FocusLost
        // TODO add your handling code here:
        if(this.text_aresta_index2.getText().length() == 0)
            this.text_aresta_index2.setText("Index do segundo ponto");
    }//GEN-LAST:event_text_aresta_index2FocusLost

    private void text_aresta_valorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_aresta_valorFocusLost
        // TODO add your handling code here:
        if(this.text_aresta_valor.getText().length() == 0)
            this.text_aresta_valor.setText("Valor da nova coneção");
    }//GEN-LAST:event_text_aresta_valorFocusLost

    private void text_adiciona_vertice_indexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_adiciona_vertice_indexFocusLost
        // TODO add your handling code here:
        if(this.text_adiciona_vertice_index.getText().length() == 0)
            this.text_adiciona_vertice_index.setText("Para adiciona pontos digite o numero de pontos que deja adicionar aqui.");
    }//GEN-LAST:event_text_adiciona_vertice_indexFocusLost

    private void text_remover_verticeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_remover_verticeFocusLost
        // TODO add your handling code here:
        if(this.text_remover_vertice.getText().length() == 0)
            this.text_remover_vertice.setText("Para remover digite o index do pontos aqui.");
    }//GEN-LAST:event_text_remover_verticeFocusLost

    private void text_swap_vertice_index1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_swap_vertice_index1FocusLost
        // TODO add your handling code here:
        if(this.text_swap_vertice_index1.getText().length() == 0)
            this.text_swap_vertice_index1.setText("Index 1");
    }//GEN-LAST:event_text_swap_vertice_index1FocusLost

    private void text_swap_vertice_index2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_swap_vertice_index2FocusLost
        // TODO add your handling code here:Index 2
        if(this.text_swap_vertice_index2.getText().length() == 0)
            this.text_swap_vertice_index2.setText("Index 2");
    }//GEN-LAST:event_text_swap_vertice_index2FocusLost

    private void text_path_fileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_path_fileFocusLost
        // TODO add your handling code here:
        if(this.text_path_file.getText().length() == 0)
            this.text_path_file.setText("Para importa o arquivo digite aqui o caminho do arquivo.( Exemplo: Files\\\\Pontos.txt )");
    }//GEN-LAST:event_text_path_fileFocusLost

    private void text_start_indexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_start_indexFocusLost
        // TODO add your handling code here:
        if(this.text_start_index.getText().length() == 0)
            this.text_start_index.setText("Index Start");
    }//GEN-LAST:event_text_start_indexFocusLost

    private void text_coleta_indexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_coleta_indexFocusLost
        // TODO add your handling code here:
        if(this.text_coleta_index.getText().length() == 0)
            this.text_coleta_index.setText("Index do ponto de colta");
    }//GEN-LAST:event_text_coleta_indexFocusLost

    private void text_banco_indexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text_banco_indexFocusLost
        // TODO add your handling code here:
        if(this.text_banco_index.getText().length() == 0)
            this.text_banco_index.setText("Index do Banco");
    }//GEN-LAST:event_text_banco_indexFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        Tela.controler = new MainCotroler();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tela().setVisible(true);
            }
        });
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Frame_Geral;
    private javax.swing.JLayeredPane Frame_dijkstra_interaçao;
    private javax.swing.JLabel Label_Remover_Aresta_info;
    private javax.swing.JPanel Panel_Aresta;
    private javax.swing.JPanel Panel_Dijkstra;
    private javax.swing.JTabbedPane Panel_Geral;
    private javax.swing.JPanel Panel_Vertice;
    private javax.swing.JButton buton_adicionar_vertice;
    private javax.swing.JButton buton_atualizar_aresta;
    private javax.swing.JButton buton_importar;
    private javax.swing.JButton buton_pathfinder;
    private javax.swing.JButton buton_remover_vertice;
    private javax.swing.JButton buton_swap_vertice;
    private javax.swing.JComboBox<String> comboBox_tipo_vertice_adicionado;
    private javax.swing.JLabel label_index_extacionamento;
    private javax.swing.JLabel label_index_extacionamento_dijskstra;
    private javax.swing.JLabel label_info_ligaçoes;
    private javax.swing.JLabel label_info_swap_vertice;
    private javax.swing.JLabel label_info_tipo_vertice_adicionado;
    private javax.swing.JLabel label_infostart_index;
    private javax.swing.JLabel label_lista_index_bancos;
    private javax.swing.JLabel label_lista_index_bancos_dijskstra;
    private javax.swing.JLabel label_lista_index_coletas;
    private javax.swing.JLabel label_lista_index_coletas_dijskstra;
    private javax.swing.JLabel label_num_vertices;
    private javax.swing.JLabel label_num_vertices_dijskstra;
    private javax.swing.JLabel label_path_Coleta_Banco;
    private javax.swing.JLabel label_path_Start_Banco;
    private javax.swing.JLabel label_path_Start_Coleta;
    private javax.swing.JTextField text_adiciona_vertice_index;
    private javax.swing.JTextField text_aresta_index1;
    private javax.swing.JTextField text_aresta_index2;
    private javax.swing.JTextField text_aresta_valor;
    private javax.swing.JTextField text_banco_index;
    private javax.swing.JTextField text_coleta_index;
    private javax.swing.JTextField text_path_file;
    private javax.swing.JTextField text_remover_vertice;
    private javax.swing.JTextField text_start_index;
    private javax.swing.JTextField text_swap_vertice_index1;
    private javax.swing.JTextField text_swap_vertice_index2;
    // End of variables declaration//GEN-END:variables
}
